#!/bin/sh
# Generate a Homebrew formula for one release tarball.
#
# The formula has to name a version and a checksum, and neither is known until
# the release tarball exists. Generating the formula from the tarball keeps the
# two from drifting apart, which is what makes a checked-in formula wrong one
# release later.
#
# Usage: homebrew-formula.sh VERSION ARCH TARBALL OUT
#   ARCH    arm64 or amd64
#   TARBALL the ens-darwin-<arch>.tar.gz from the release
set -eu

if [ "$#" -lt 4 ]; then
	echo "usage: homebrew-formula.sh VERSION ARCH TARBALL OUT" >&2
	exit 2
fi

VERSION=$1
ARCH=$2
TARBALL=$3
OUT=$4

case "$ARCH" in
amd64 | arm64) ;;
*)
	echo "unsupported formula arch: $ARCH" >&2
	exit 2
	;;
esac

if [ ! -f "$TARBALL" ]; then
	echo "missing tarball: $TARBALL" >&2
	exit 2
fi

# The release runner is macOS, so shasum is the tool there. sha256sum covers
# a Linux run for anyone generating the formula elsewhere.
if command -v sha256sum >/dev/null 2>&1; then
	SHA=$(sha256sum "$TARBALL" | cut -d' ' -f1)
else
	SHA=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
fi

mkdir -p "$(dirname "$OUT")"
# The first two lines are what brew style asks for, so the generated formula
# passes brew style without a later fix-up commit.
cat >"$OUT" <<EOF
# typed: strict
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Ens < Formula
  desc "P2P overlay network: QUIC first, relay as fallback"
  homepage "https://github.com/fdaio/enserie"
  url "https://github.com/fdaio/enserie/releases/download/v${VERSION}/ens-darwin-${ARCH}.tar.gz"
  sha256 "$SHA"

  def install
    bin.install "ens"
  end

  # Opening a TUN needs root, so the test stays on the one command that does
  # not. A formula whose test needed sudo would fail for every user who runs
  # brew test without it.
  test do
    assert_match version.to_s, shell_output("#{bin}/ens version")
  end
end
EOF
echo "wrote $OUT for v$VERSION ($ARCH)" >&2